services:
  mailer:
    container_name: setup-laravel-mailer
    image: axllent/mailpit
    ports:
      - "8025"
      - "32770:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - setup-laravel-network

  php:
    container_name: setup-laravel-php
    build:
      context: ./docker/php
      dockerfile: dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./backend:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup-laravel-network
    depends_on:
      - mysql
      - redis

  nginx:
    container_name: setup-laravel-nginx
    build:
      context: ./docker/nginx
      dockerfile: dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup-laravel-network
    depends_on:
      - php

  mysql:
    container_name: setup-laravel-mysql
    image: mysql:8.0
    restart: always
    tty: true
    volumes:
      - setup-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - setup-laravel-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: developer
      MYSQL_PASSWORD: 123456

  redis:
    container_name: setup-laravel-redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - setup-laravel-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  setup-laravel-network:
    driver: bridge

volumes:
  setup-data:
    driver: local
  redis_data:
    driver: local
